#!/bin/sh

# Uses the following variables from the environment:
# OBP_API_HOSTNAME

PROPS_OBP_API="/opt/OBP/OBP-API/src/main/resources/props/default.props"


# check environment
if [ -z ${OBP_API_HOSTNAME} ]; then
	echo "ERROR: OBP_API_HOSTNAME not set!"
	exit 1;
fi

# API
echo "Replacing properties for API"
/bin/sed -i "s|hostname=.*|hostname=${OBP_API_HOSTNAME}|g" ${PROPS_OBP_API}


# Start supervisor
exec /etc/init.d/supervisor start
